language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
script:
  - xctool -workspace Whiteplanes.xcworkspace -scheme Whiteplanes -sdk iphonesimulator clean build test


